version: '2'
services:
    testwwproj-app:
        image: testwwproj
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://testwwproj-mysql:3306/testwwproj?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8088:8088
    testwwproj-mysql:
        extends:
            file: mysql.yml
            service: testwwproj-mysql
